Ticket7350
ISISComputingGroup/EPICS-Tjmpap pull request #1
Opened 2022-09-21 12:58 UTC by NikolaRoev

https://github.com/ISISComputingGroup/IBEX/issues/7350

2022-10-16 20:18 UTC, FreddieAkeroyd commented on tjmpapSup/tjmpap.proto
> +
Is a Db file missing? I couldn't see anywhere that used this protocol file

2022-10-21 10:15 UTC, LilithCole requested changes

2022-10-21 10:15 UTC, LilithCole commented on tjmpapSup/tjmpap.template
> +}
When does this record actually process? SCAN is Passive but I don't see anything linking to it

2022-10-21 10:15 UTC, LilithCole commented on tjmpapSup/tjmpap.template
> +}
Likewise for this input

2022-10-21 10:15 UTC, LilithCole commented on Makefile
> +    .\system_tests\run_tests.bat
makefile requires a tab indentation here

2022-10-24 08:57 UTC, NikolaRoev commented on tjmpapSup/tjmpap.template
> +}
Doesn't using `CP` in the `INP` field mean that the record is processed when the input updates?

2022-11-07 09:42 UTC, LilithCole approved these changes

2022-11-07 09:42 UTC, merged